# Groups Assignment – Introduction to Data Science 

##          Group n° 1

### Arnaud WATUSADISI MAVAKALA
### Serigne Fallou NDIAYE
### Awadi Abalo KATANGA
### Netho Junior KANINGINI LUTALA

  ##  Tache groupe 1 / Task group 1

## ENGLISH
### The task in this project was to calculate and present in the same Dataframe: The average of the population (µ) of each region, the standard deviation (σ) and the calculation of the coefficient of variation (Cv) and conclude

### Then the other operation was to obtain the minimum area of each region and complete with the corresponding country name on the same line in the Serie where the Dataframe obtained.

## FRENCH
### Calculer et présenter dans un même Dataframe : La moyenne de la population (µ) de chaque région, l’ecart type (σ) et le calcul du coefficient de variation (Cv) et conclure 

### Obtenir la superficie minimale de chaque région et compléter avec le nom de pays correspondant sur la même  ligne dans la Serie ou le Dataframe obtenu.

## IMPORTATION DES MODULES / IMPORT OF MODULES

In [8]:

import pandas as pd
import numpy as np
import csv

## IMPORTATION de l'Afrique de l'Est / IMPORT from East Africa

In [9]:
#'/home/ndoye/Documents/AfriqueduNord.csv'
#path = '/home/ndoye/Documents/'
path = '/Users/honore Pc/Documents/data science/Projet/GROUPE_01/'

#C:\Users\honore Pc\Documents\data science\Projet\GROUPE_01
path_  = path + 'AfriqueEst.csv'
print(path_)

/Users/honore Pc/Documents/data science/Projet/GROUPE_01/AfriqueEst.csv

## vérification de fichier l'Afique de l'Est / East Africa file verification

In [ ]:
cat $path + 'AfriqueEst.csv'

## Affichons l'afrique de l'Est / Let's display east africa

In [12]:
af_Est = pd.read_csv(path + '/AfriqueEst.csv', 
                      sep = ',',
                      decimal=",")
af_Est.columns = ['pays', 'superficie','population','densite','capitale']

pays=af_Est.columns[0]

af_Est

,pays,superficie,population,densite,capitale
0,Érythrée (Dawlat Iritriya (ar) (fr)),121320,5869970,50.00,Asmara
1,Éthiopie (YeItyopya Federalawi Dimokrasiyawi...,1127127,105350020,88.00,Addis-Abeba
2,Somalie (Jamhuuriyadda Federaalka Soomaaliya...,637657,1259029,18.00,Mogadiscio
3,Djibouti (République de Djibouti (fr)),25030,810179,21.00,Djibouti
4,Soudan du Sud (Republic of South Sudan (en) ...,619745,12530717,20.20,Djouba
5,Kenya (Jamhuri ya Kenya (sw) (fr)),580367,41800000,72.02,Nairobi
6,Ouganda (Jamhuri ya Uganda (sw) (fr)),241550,41487965,172.00,Kampala
7,Tanzanie (Jamhuri ya Muungano wa Tanzania (s...,945087,57310019,52.00,Dodoma
8,Rwanda (Jamhuri ya Rwanda (sw) (fr)),26338,12187400,462.70,Kigali
9,Burundi (Jamhuri ya burundi (sw) (fr)),27834,11099298,398.70,Gitega
10,Seychelles (Repiblik Sesel (crs) (fr)),455,92430,203.10,Victoria

## le type de donnée de l'Afrique de l'Est / the type of data from East Africa

In [13]:

af_Est.dtypes

pays           object
superficie      int64
population      int64
densite       float64
capitale       object
dtype: object

## fonction pour nettoyer / function to clean

In [14]:

###########################################################################################
## fonction pour nettoyer / function to clean

def fonction(afrique, pays):
    list_Pays=list(afrique[pays])
    Pays_sans=[list_Pays[i].strip() for i in range(len(list_Pays))]
    Pays_Preopre=[Pays_sans[i].split()[0] for i in range(len(list_Pays))]
    return  Pays_Preopre

nE=fonction(af_Est, pays)
print(nE)

###########################################################################################

for i in range(len(nE)):
    af_Est.at[i,pays]= nE[i]

## remplacer soudans du sud 
af_Est.at[4,pays]= 'Soudan du sud'

print("**************************************************************")
## voir les type de caractere 
print(af_Est.dtypes)
print("**************************************************************")
###########################################################################################
##on index 
af_Est= af_Est.set_index(pays)
print(af_Est)
print("**************************************************************")

#af_Est.index.name=None

af_Est

['Érythrée', 'Éthiopie', 'Somalie', 'Djibouti', 'Soudan', 'Kenya', 'Ouganda', 'Tanzanie', 'Rwanda', 'Burundi', 'Seychelles']
**************************************************************
pays           object
superficie      int64
population      int64
densite       float64
capitale       object
dtype: object
**************************************************************
               superficie  population  densite     capitale
pays
Érythrée           121320     5869970    50.00       Asmara
Éthiopie          1127127   105350020    88.00  Addis-Abeba
Somalie            637657     1259029    18.00   Mogadiscio
Djibouti            25030      810179    21.00     Djibouti
Soudan du sud      619745    12530717    20.20       Djouba
Kenya              580367    41800000    72.02      Nairobi
Ouganda            241550    41487965   172.00      Kampala
Tanzanie           945087    57310019    52.00       Dodoma
Rwanda              26338    12187400   462.70       Kigali
Burundi             27834    11099298   398.70       Gitega
Seychelles            455       92430   203.10     Victoria
**************************************************************

               superficie  population  densite     capitale
pays
Érythrée           121320     5869970    50.00       Asmara
Éthiopie          1127127   105350020    88.00  Addis-Abeba
Somalie            637657     1259029    18.00   Mogadiscio
Djibouti            25030      810179    21.00     Djibouti
Soudan du sud      619745    12530717    20.20       Djouba
Kenya              580367    41800000    72.02      Nairobi
Ouganda            241550    41487965   172.00      Kampala
Tanzanie           945087    57310019    52.00       Dodoma
Rwanda              26338    12187400   462.70       Kigali
Burundi             27834    11099298   398.70       Gitega
Seychelles            455       92430   203.10     Victoria

## Afrique Australe / Southern Africa

In [ ]:
cat $path + 'AfriqueAustrale.csv'

In [15]:
## affichons sle tableau

af_Australe= pd.read_csv(path + '/AfriqueAustrale.csv', 
                      sep = ',',
                      decimal=",")
af_Australe.columns = ['pays', 'superficie','population','densite','capitale']

paysA=af_Australe.columns[0]

print(paysA)

nA=fonction(af_Australe, paysA)
print(nA)
###########################################################################################

for i in range(len(nA)):
    af_Australe.at[i,pays]= nA[i]
## remplacer soudans du sud 
af_Australe.at[0,pays]= 'Afrique du sud'
print("**************************************************************")
## voir les type de caractere 
print(af_Australe.dtypes)
print("**************************************************************")
###########################################################################################
##on index 
af_Australe= af_Australe.set_index(pays)
print(af_Australe)
print("**************************************************************")

#af_Australe.index.name=None
af_Australe

pays
['Afrique', 'Botswana', 'Comores', 'Swaziland', 'Lesotho', 'Madagascar', 'Malawi', 'Maurice', 'Mozambique', 'Namibie', 'Zimbabwe', 'Zambie']
**************************************************************
pays           object
superficie      int64
population      int64
densite       float64
capitale       object
dtype: object
**************************************************************
                superficie  population  densite      capitale
pays
Afrique du sud     1219912    55653654    46.00      Pretoria
Botswana            581726     2209208     3.80      Gaborone
Comores               2612      813912   343.00        Moroni
Swaziland            17363     1451428    82.70       Lobamba
Lesotho              30355     1924381    63.00        Maseru
Madagascar          587041    24430325    41.61  Antananarivo
Malawi              118844    18091575   152.00      Lilongwe
Maurice               2040     1259838   630.00    Port-Louis
Mozambique          801590    25900000    32.00        Maputo
Namibie             825418     2484780     3.00      Windhoek
Zimbabwe            390245    14030368    36.00        Harare
Zambie              752614    15066266    20.00        Lusaka
**************************************************************

                superficie  population  densite      capitale
pays
Afrique du sud     1219912    55653654    46.00      Pretoria
Botswana            581726     2209208     3.80      Gaborone
Comores               2612      813912   343.00        Moroni
Swaziland            17363     1451428    82.70       Lobamba
Lesotho              30355     1924381    63.00        Maseru
Madagascar          587041    24430325    41.61  Antananarivo
Malawi              118844    18091575   152.00      Lilongwe
Maurice               2040     1259838   630.00    Port-Louis
Mozambique          801590    25900000    32.00        Maputo
Namibie             825418     2484780     3.00      Windhoek
Zimbabwe            390245    14030368    36.00        Harare
Zambie              752614    15066266    20.00        Lusaka

# Afrique Centrale / Central Africa

In [16]:
af_centrale = pd.read_csv(path + '/AfriqueCentral.csv', 
                          sep = ',',
                          decimal=",")
af_centrale.columns = ['pays', 'superficie','population','densite','capitale']
af_centrale.at[0,'pays']= 'Angola'
af_centrale = af_centrale.set_index('pays')
#af_centrale.index.name=None
af_centrale

,superficie,population,densite,capitale
pays,,,,
Angola,1246700,29784000,23.9,Luanda
Cameroun,475650,24054000,50.9,Yaoundé
Gabon,267668,2025000,7.9,Libreville
Guinée équatoriale,28052,1268000,45.2,Malabo
République centrafricaine,622984,4659000,7.5,Bangui
République démocratique du Congo,2344858,81340000,35.9,Kinshasa
République du Congo,342000,5261000,15.4,Brazzaville
Sao Tomé-et-Principe,964,204000,212.8,São Tomé
Tchad,1284000,14900000,11.8,N'Djaména

## Afrique du Nord / North Africa

In [17]:
af_nord = pd.read_csv(path + '/AfriqueduNord.csv', 
                      sep = ',',
                      decimal=",",
                      index_col= 'pays ')
af_nord.columns = ['superficie','population','densite','capitale']
af_nord

            superficie  population  densite   capitale
pays
  Algérie      2381740    40606052    17.05     Alger
  Égypte       1001450    95688681    96.00  Le Caire
  Libye        1759540     6293253     3.58   Tripoli
  Maroc         710850    35276786    73.10     Rabat
  Tunisie       163610    11403248    63.00     Tunis

## Afrique de l'Ouest / West Africa

In [18]:
# Création du data frame 'af_ouest' en utilisant un dictionaire

af_ouest = pd.DataFrame({'superficie':[114763,272967,4033,322463,11295,238533,245857,36125,111369,1241238,1025520,1267000,
                                             923768,196722,71740,56785],
                         'population':[9352000,17482000,505000,20595000,1825000,25546000,10481000, 1580000,4245000,16319000,
                                             3623000,16644000,166629000,13108000,6126000,6283000],    
                         'densite':[81,64,125,64,162,107,43,44,38,13,4,13,180,67,85,111],    
                         'capitale':['Porto-Novo','Ouagadougou','Praia','Yamoussoukro','Banjul','Accra','Conakry','Bissau',
                                            'Monrovia','Bamako','Nouakchott','Niamey','Abuja','Dakar','Freetown','Lomé']
                         }
                         
                        )
af_ouest = af_ouest[['superficie','densite','population','capitale']]
af_ouest["pays"]= ['Bénin','Burkina Faso','Cap-Vert','Côte d\'Ivoire','Gambie','Ghana','Guinée','Guinée-Bissau',
                                 'Liberia','Mali','Mauritanie','Niger','Nigeria','Sénégal','Sierra Leone','Togo']

af_ouest = af_ouest.set_index('pays')
print(" ##################################   afrique de l'ouest #################################")
af_ouest

 ##################################   afrique de l'ouest #################################

               superficie  densite  population      capitale
pays
Bénin              114763       81     9352000    Porto-Novo
Burkina Faso       272967       64    17482000   Ouagadougou
Cap-Vert             4033      125      505000         Praia
Côte d'Ivoire      322463       64    20595000  Yamoussoukro
Gambie              11295      162     1825000        Banjul
Ghana              238533      107    25546000         Accra
Guinée             245857       43    10481000       Conakry
Guinée-Bissau       36125       44     1580000        Bissau
Liberia            111369       38     4245000      Monrovia
Mali              1241238       13    16319000        Bamako
Mauritanie        1025520        4     3623000    Nouakchott
Niger             1267000       13    16644000        Niamey
Nigeria            923768      180   166629000         Abuja
Sénégal            196722       67    13108000         Dakar
Sierra Leone        71740       85     6126000      Freetown
Togo                56785      111     6283000          Lomé

## Concatener / Concatenate  af_ouest, af_nord, af_centrale,af_Est,af_Australe

In [19]:

afrique=[af_ouest, af_nord, af_centrale,af_Est,af_Australe]
all_region = pd.concat(afrique,sort=True )
all_region

,capitale,densite,population,superficie
Bénin,Porto-Novo,81.00,9352000,114763
Burkina Faso,Ouagadougou,64.00,17482000,272967
Cap-Vert,Praia,125.00,505000,4033
Côte d'Ivoire,Yamoussoukro,64.00,20595000,322463
Gambie,Banjul,162.00,1825000,11295
Ghana,Accra,107.00,25546000,238533
Guinée,Conakry,43.00,10481000,245857
Guinée-Bissau,Bissau,44.00,1580000,36125
Liberia,Monrovia,38.00,4245000,111369
Mali,Bamako,13.00,16319000,1241238
Mauritanie,Nouakchott,4.00,3623000,1025520
Niger,Niamey,13.00,16644000,1267000
Nigeria,Abuja,180.00,166629000,923768
Sénégal,Dakar,67.00,13108000,196722
Sierra Leone,Freetown,85.00,6126000,71740
Togo,Lomé,111.00,6283000,56785
Algérie,Alger,17.05,40606052,2381740
Égypte,Le Caire,96.00,95688681,1001450
Libye,Tripoli,3.58,6293253,1759540
Maroc,Rabat,73.10,35276786,710850
Tunisie,Tunis,63.00,11403248,163610
Angola,Luanda,23.90,29784000,1246700
Cameroun,Yaoundé,50.90,24054000,475650
Gabon,Libreville,7.90,2025000,267668
Guinée équatoriale,Malabo,45.20,1268000,28052
République centrafricaine,Bangui,7.50,4659000,622984
République démocratique du Congo,Kinshasa,35.90,81340000,2344858
République du Congo,Brazzaville,15.40,5261000,342000
Sao Tomé-et-Principe,São Tomé,212.80,204000,964
Tchad,N'Djaména,11.80,14900000,1284000
Érythrée,Asmara,50.00,5869970,121320
Éthiopie,Addis-Abeba,88.00,105350020,1127127
Somalie,Mogadiscio,18.00,1259029,637657
Djibouti,Djibouti,21.00,810179,25030
Soudan du sud,Djouba,20.20,12530717,619745
Kenya,Nairobi,72.02,41800000,580367
Ouganda,Kampala,172.00,41487965,241550
Tanzanie,Dodoma,52.00,57310019,945087
Rwanda,Kigali,462.70,12187400,26338
Burundi,Gitega,398.70,11099298,27834
Seychelles,Victoria,203.10,92430,455
Afrique du sud,Pretoria,46.00,55653654,1219912
Botswana,Gaborone,3.80,2209208,581726
Comores,Moroni,343.00,813912,2612
Swaziland,Lobamba,82.70,1451428,17363
Lesotho,Maseru,63.00,1924381,30355
Madagascar,Antananarivo,41.61,24430325,587041
Malawi,Lilongwe,152.00,18091575,118844
Maurice,Port-Louis,630.00,1259838,2040
Mozambique,Maputo,32.00,25900000,801590
Namibie,Windhoek,3.00,2484780,825418
Zimbabwe,Harare,36.00,14030368,390245
Zambie,Lusaka,20.00,15066266,752614

## voir le type de l'all_region / see the type of all_region

In [20]:
all_region.dtypes

capitale       object
densite       float64
population      int64
superficie      int64
dtype: object

## fonction pour Inserer la region / function to insert region

In [21]:

def regionAfrique(afrique0,  region , afrique1):
    afrique0[region] = [afrique1]*len(afrique0)

In [22]:
Renommer_Afrique=["Afrique de l'ouest ", "Afrique du Nord", "Afrique Centrale","Afrique de l'Est ","Afrique Autrale"]
for i in range(len(afrique)):
    regionAfrique(afrique[i],'region',Renommer_Afrique[i])

In [23]:
afrique=[af_ouest, af_nord, af_centrale,af_Est,af_Australe]
all_region = pd.concat(afrique,sort=True )
all_region

,capitale,densite,population,region,superficie
Bénin,Porto-Novo,81.00,9352000,Afrique de l'ouest,114763
Burkina Faso,Ouagadougou,64.00,17482000,Afrique de l'ouest,272967
Cap-Vert,Praia,125.00,505000,Afrique de l'ouest,4033
Côte d'Ivoire,Yamoussoukro,64.00,20595000,Afrique de l'ouest,322463
Gambie,Banjul,162.00,1825000,Afrique de l'ouest,11295
Ghana,Accra,107.00,25546000,Afrique de l'ouest,238533
Guinée,Conakry,43.00,10481000,Afrique de l'ouest,245857
Guinée-Bissau,Bissau,44.00,1580000,Afrique de l'ouest,36125
Liberia,Monrovia,38.00,4245000,Afrique de l'ouest,111369
Mali,Bamako,13.00,16319000,Afrique de l'ouest,1241238
Mauritanie,Nouakchott,4.00,3623000,Afrique de l'ouest,1025520
Niger,Niamey,13.00,16644000,Afrique de l'ouest,1267000
Nigeria,Abuja,180.00,166629000,Afrique de l'ouest,923768
Sénégal,Dakar,67.00,13108000,Afrique de l'ouest,196722
Sierra Leone,Freetown,85.00,6126000,Afrique de l'ouest,71740
Togo,Lomé,111.00,6283000,Afrique de l'ouest,56785
Algérie,Alger,17.05,40606052,Afrique du Nord,2381740
Égypte,Le Caire,96.00,95688681,Afrique du Nord,1001450
Libye,Tripoli,3.58,6293253,Afrique du Nord,1759540
Maroc,Rabat,73.10,35276786,Afrique du Nord,710850
Tunisie,Tunis,63.00,11403248,Afrique du Nord,163610
Angola,Luanda,23.90,29784000,Afrique Centrale,1246700
Cameroun,Yaoundé,50.90,24054000,Afrique Centrale,475650
Gabon,Libreville,7.90,2025000,Afrique Centrale,267668
Guinée équatoriale,Malabo,45.20,1268000,Afrique Centrale,28052
République centrafricaine,Bangui,7.50,4659000,Afrique Centrale,622984
République démocratique du Congo,Kinshasa,35.90,81340000,Afrique Centrale,2344858
République du Congo,Brazzaville,15.40,5261000,Afrique Centrale,342000
Sao Tomé-et-Principe,São Tomé,212.80,204000,Afrique Centrale,964
Tchad,N'Djaména,11.80,14900000,Afrique Centrale,1284000
Érythrée,Asmara,50.00,5869970,Afrique de l'Est,121320
Éthiopie,Addis-Abeba,88.00,105350020,Afrique de l'Est,1127127
Somalie,Mogadiscio,18.00,1259029,Afrique de l'Est,637657
Djibouti,Djibouti,21.00,810179,Afrique de l'Est,25030
Soudan du sud,Djouba,20.20,12530717,Afrique de l'Est,619745
Kenya,Nairobi,72.02,41800000,Afrique de l'Est,580367
Ouganda,Kampala,172.00,41487965,Afrique de l'Est,241550
Tanzanie,Dodoma,52.00,57310019,Afrique de l'Est,945087
Rwanda,Kigali,462.70,12187400,Afrique de l'Est,26338
Burundi,Gitega,398.70,11099298,Afrique de l'Est,27834
Seychelles,Victoria,203.10,92430,Afrique de l'Est,455
Afrique du sud,Pretoria,46.00,55653654,Afrique Autrale,1219912
Botswana,Gaborone,3.80,2209208,Afrique Autrale,581726
Comores,Moroni,343.00,813912,Afrique Autrale,2612
Swaziland,Lobamba,82.70,1451428,Afrique Autrale,17363
Lesotho,Maseru,63.00,1924381,Afrique Autrale,30355
Madagascar,Antananarivo,41.61,24430325,Afrique Autrale,587041
Malawi,Lilongwe,152.00,18091575,Afrique Autrale,118844
Maurice,Port-Louis,630.00,1259838,Afrique Autrale,2040
Mozambique,Maputo,32.00,25900000,Afrique Autrale,801590
Namibie,Windhoek,3.00,2484780,Afrique Autrale,825418
Zimbabwe,Harare,36.00,14030368,Afrique Autrale,390245
Zambie,Lusaka,20.00,15066266,Afrique Autrale,752614

## Indexons le pays / Let's index the country

In [24]:
Copie_Afrique=all_region.copy()

Copie_Afrique.index.name="pays"
print(len(Copie_Afrique))
Copie_Afrique

53

,capitale,densite,population,region,superficie
pays,,,,,
Bénin,Porto-Novo,81.00,9352000,Afrique de l'ouest,114763
Burkina Faso,Ouagadougou,64.00,17482000,Afrique de l'ouest,272967
Cap-Vert,Praia,125.00,505000,Afrique de l'ouest,4033
Côte d'Ivoire,Yamoussoukro,64.00,20595000,Afrique de l'ouest,322463
Gambie,Banjul,162.00,1825000,Afrique de l'ouest,11295
Ghana,Accra,107.00,25546000,Afrique de l'ouest,238533
Guinée,Conakry,43.00,10481000,Afrique de l'ouest,245857
Guinée-Bissau,Bissau,44.00,1580000,Afrique de l'ouest,36125
Liberia,Monrovia,38.00,4245000,Afrique de l'ouest,111369
Mali,Bamako,13.00,16319000,Afrique de l'ouest,1241238
Mauritanie,Nouakchott,4.00,3623000,Afrique de l'ouest,1025520
Niger,Niamey,13.00,16644000,Afrique de l'ouest,1267000
Nigeria,Abuja,180.00,166629000,Afrique de l'ouest,923768
Sénégal,Dakar,67.00,13108000,Afrique de l'ouest,196722
Sierra Leone,Freetown,85.00,6126000,Afrique de l'ouest,71740
Togo,Lomé,111.00,6283000,Afrique de l'ouest,56785
Algérie,Alger,17.05,40606052,Afrique du Nord,2381740
Égypte,Le Caire,96.00,95688681,Afrique du Nord,1001450
Libye,Tripoli,3.58,6293253,Afrique du Nord,1759540
Maroc,Rabat,73.10,35276786,Afrique du Nord,710850
Tunisie,Tunis,63.00,11403248,Afrique du Nord,163610
Angola,Luanda,23.90,29784000,Afrique Centrale,1246700
Cameroun,Yaoundé,50.90,24054000,Afrique Centrale,475650
Gabon,Libreville,7.90,2025000,Afrique Centrale,267668
Guinée équatoriale,Malabo,45.20,1268000,Afrique Centrale,28052
République centrafricaine,Bangui,7.50,4659000,Afrique Centrale,622984
République démocratique du Congo,Kinshasa,35.90,81340000,Afrique Centrale,2344858
République du Congo,Brazzaville,15.40,5261000,Afrique Centrale,342000
Sao Tomé-et-Principe,São Tomé,212.80,204000,Afrique Centrale,964
Tchad,N'Djaména,11.80,14900000,Afrique Centrale,1284000
Érythrée,Asmara,50.00,5869970,Afrique de l'Est,121320
Éthiopie,Addis-Abeba,88.00,105350020,Afrique de l'Est,1127127
Somalie,Mogadiscio,18.00,1259029,Afrique de l'Est,637657
Djibouti,Djibouti,21.00,810179,Afrique de l'Est,25030
Soudan du sud,Djouba,20.20,12530717,Afrique de l'Est,619745
Kenya,Nairobi,72.02,41800000,Afrique de l'Est,580367
Ouganda,Kampala,172.00,41487965,Afrique de l'Est,241550
Tanzanie,Dodoma,52.00,57310019,Afrique de l'Est,945087
Rwanda,Kigali,462.70,12187400,Afrique de l'Est,26338
Burundi,Gitega,398.70,11099298,Afrique de l'Est,27834
Seychelles,Victoria,203.10,92430,Afrique de l'Est,455
Afrique du sud,Pretoria,46.00,55653654,Afrique Autrale,1219912
Botswana,Gaborone,3.80,2209208,Afrique Autrale,581726
Comores,Moroni,343.00,813912,Afrique Autrale,2612
Swaziland,Lobamba,82.70,1451428,Afrique Autrale,17363
Lesotho,Maseru,63.00,1924381,Afrique Autrale,30355
Madagascar,Antananarivo,41.61,24430325,Afrique Autrale,587041
Malawi,Lilongwe,152.00,18091575,Afrique Autrale,118844
Maurice,Port-Louis,630.00,1259838,Afrique Autrale,2040
Mozambique,Maputo,32.00,25900000,Afrique Autrale,801590
Namibie,Windhoek,3.00,2484780,Afrique Autrale,825418
Zimbabwe,Harare,36.00,14030368,Afrique Autrale,390245
Zambie,Lusaka,20.00,15066266,Afrique Autrale,752614

###        2. Tache groupe 1 / Task group 1
### Obtenir la superficie minimale de chaque région et compléter avec le nom de pays correspondant sur la même  ligne dans la Serie ou le Dataframe obtenu. 
### /
### Obtain the minimum area of ​​each region and complete with the corresponding country name on the same line in the Serie or Dataframe obtained.

In [25]:
df_= Copie_Afrique[['superficie','region']].groupby(['region']).min()
n=Copie_Afrique.reset_index(level = ['pays'],inplace =False) 
nn=n[["pays",'superficie','region']].merge(df_)
nn

                      pays  superficie               region
0                 Cap-Vert        4033  Afrique de l'ouest
1                 Tunisie       163610      Afrique du Nord
2    Sao Tomé-et-Principe          964     Afrique Centrale
3               Seychelles         455    Afrique de l'Est
4                  Maurice        2040      Afrique Autrale

In [26]:
moyenne  = af_ouest.mean()

### Calculate and present in the same Dataframe: The average of the population (µ) of each region, the standard deviation (σ) and the calculation of the coefficient of variation (Cv).

###  Calculer et présenter dans un même Dataframe : La moyenne de la population (µ) de chaque région, l’ecart type (σ) et le calcul du coefficient de variation (Cv).

In [27]:
#cv =  lambda x: np.std(x) / np.mean(x)
df = Copie_Afrique[['population','region']].groupby(['region']).agg([np.mean, np.std])
df.columns = ['moyenne', 'ecart type']
print("\n")
print("                                 population                                     ")

df

                                 population

                          moyenne    ecart type
region
Afrique Autrale      1.360964e+07  1.627204e+07
Afrique Centrale     1.816611e+07  2.595417e+07
Afrique de l'Est     2.634518e+07  3.268372e+07
Afrique de l'ouest   2.002144e+07  3.979997e+07
Afrique du Nord      3.785360e+07  3.554852e+07

In [28]:
df['coef_var']=df['ecart type']/df['moyenne']
df

                          moyenne    ecart type  coef_var
region
Afrique Autrale      1.360964e+07  1.627204e+07  1.195626
Afrique Centrale     1.816611e+07  2.595417e+07  1.428714
Afrique de l'Est     2.634518e+07  3.268372e+07  1.240595
Afrique de l'ouest   2.002144e+07  3.979997e+07  1.987868
Afrique du Nord      3.785360e+07  3.554852e+07  0.939105

In [29]:
df3=pd.merge(nn, df, on='region', how='right')
print("\n\n                min                              population ")


df3

                min                              population

,pays,superficie,region,moyenne,ecart type,coef_var
0,Cap-Vert,4033,Afrique de l'ouest,2.002144e+07,3.979997e+07,1.987868
1,Tunisie,163610,Afrique du Nord,3.785360e+07,3.554852e+07,0.939105
2,Sao Tomé-et-Principe,964,Afrique Centrale,1.816611e+07,2.595417e+07,1.428714
3,Seychelles,455,Afrique de l'Est,2.634518e+07,3.268372e+07,1.240595
4,Maurice,2040,Afrique Autrale,1.360964e+07,1.627204e+07,1.195626

## Conclusion

#### Starting from coefficient of variation; we find that the populations of North Africa are not very dispersed around the average and those of West Africa are very dispersed around the average. / Partant de coefficient de variation ; nous constatons que les populations de l'Afrique du nord sont peu dispersées autour de la moyenne et celles de l'Afrique de l'ouest sont très dispersées autour de la moyenne.
#### The measurement of the standard deviation is an index of dispersion sensitive to the average value and to the unit of the values used, but the coefficient of variation allowed us to obtain a general index independent of the units of measurement used. / La mesure de l'ecart type est un indice de dispersion  sensible à la valeur moyenne et à l'unité des valeurs utilisées mais le coeficient de variation nous a permi d'obtenir un indice général independant des unités de mésure employées.

<img src="image.gif" alt="" />

<img src="image.gif" alt="" />